apiVersion: batch/v1
kind: Job
metadata:
  name: job3
spec:
  completions: 2
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["echo", "it will complete twice"]
      restartPolicy: Never
