apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-job
spec:
  activeDeadlineSeconds: 15
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "25"]
      restartPolicy: Never
