apiVersion: batch/v1
kind: Job
metadata:
  name: job3
spec:
  completions: 2
  parallelism: 2
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["echo", "2 jobs will run in parallel, twice"]
      restartPolicy: Never
