apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-job
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["cat", "/etc"]
      restartPolicy: Never
