apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-job
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["echo", "This is k8s"]
      restartPolicy: Never
