apiVersion: batch/v1
kind: Job
metadata:
  name: job2
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "120"]
      restartPolicy: Never
