apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  volumes:
  - name: mysql-vol
    configMap:
      name: mysql-config
      items:
        - key: my.cnf
          path: my.cnf
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
    volumeMounts:
    - name: mysql-vol
      mountPath: /vol
