apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  volumes:
  - name: vol
    secret:
      secretName: secret1
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
    volumeMounts:
    - name: vol
      mountPath: /vol
