apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
    env:
    - name: trainer
      valueFrom:
        configMapKeyRef:
          name: configmap1
          key: trainer
    - name: training
      valueFrom:
        configMapKeyRef:
          name: configmap1
          key: training
