apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  volumes:
  - name: vol
    configMap:
      name: configmap1
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
    volumeMounts:
    - name: vol
      mountPath: /vol
