apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  restartPolicy: OnFailure
  volumes:
  - name: pvc
    persistentVolumeClaim:
     claimName: pvc
  containers:
  - name: busybox
    image: busybox:stable
    command: ['sh', '-c', 'sleep 100000000']
    volumeMounts:
    - name: pvc
      mountPath: /data
